version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - timReynolds
  ignore:
  - dependency-name: ts-jest
    versions:
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
